name: Test SSH Connection

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # This is required
    environment:
      name: minibit_prod

    steps:
      - uses: actions/checkout@v4

      - name: Show variables
        run: |
          echo "Server: ${{ secrets.SERVER_IP }}"
          echo "User: ${{ secrets.SERVER_IP }}"
