name: Test SSH Connection

on:
  push:
    branches: [ master ]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    # 👇 IMPORTANTE: Especifica el entorno donde están los secrets
    environment: minibit_prod
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "¡Conexión exitosa!"
            whoami
            pwd
            ls -la